apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: granite3.2-8b-cpu
    serving.kserve.io/deploymentMode: RawDeployment
  name: granite32-8b-cpu
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '8'
          memory: 20Gi
        requests:
          cpu: '4'
          memory: 8Gi
      runtime: granite32-8b-cpu
      storageUri: 'oci://quay.io/redhat-ai-services/modelcar-catalog:granite-3.2-8b-instruct'
