apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["habana.ai/gaudi"]'
    opendatahub.io/template-display-name: vLLM Intel Gaudi Accelerator ServingRuntime for KServe
    opendatahub.io/accelerator-name: gaudi-hpu-profile
    opendatahub.io/template-name: vllm-gaudi-runtime
    openshift.io/display-name: llama32-1b-hpu
  name: llama32-1b-hpu
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
  containers:
    - args:
        - '--port=8080'
        - '--model=/mnt/models'
        - '--served-model-name={{.Name}}'
        - '--enable-auto-tool-choice'
        - '--tool-call-parser'
        - llama3_json
        - '--chat-template'
        - /app/data/template/tool_chat_template_llama3.2_json.jinja
        - '--max-model-len'
        - '128000'
        - '--gpu-memory-utilization'
        - '0.85'
        - '--block-size'
        - '128'
        - '--dtype'
        - 'bfloat16'
      command:
        - python
        - '-m'
        - vllm.entrypoints.openai.api_server
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      image: 'quay.io/modh/vllm@sha256:af6a071be36d8a99476f145d1589d7ede97d2760b93335b14ca26de7417e438c'
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
